export type OfficialDocEntry = {
  readonly id: string;
  readonly product: string;
  readonly title: string;
  readonly url: string;
  readonly kind: "docs" | "api" | "cli" | "mcp" | "press";
};

export const officialDocsIndex: readonly OfficialDocEntry[] = [
  {
    id: "salesforce-mcp-solutions",
    product: "Salesforce",
    title: "Salesforce MCP Solutions",
    url: "https://developer.salesforce.com/docs/ai/agentforce/guide/mcp.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-mcp-reference",
    product: "Salesforce",
    title: "Hosted MCP Servers Reference",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/references/reference/servers-reference.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-sobject-reads",
    product: "Salesforce",
    title: "Hosted MCP SObject Reads",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/sobject-reads.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-sobject-all",
    product: "Salesforce",
    title: "Hosted MCP SObject All",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/sobject-all.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-sobject-mutations",
    product: "Salesforce",
    title: "Hosted MCP SObject Mutations",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/references/reference/sobject-mutations.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-sobject-deletes",
    product: "Salesforce",
    title: "Hosted MCP SObject Deletes",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/sobject-deletes.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-api-catalog",
    product: "Salesforce",
    title: "Hosted MCP API Catalog",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/references/reference/api-catalog.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-flows",
    product: "Salesforce",
    title: "Hosted MCP Flows",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/flows.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-invocable-actions",
    product: "Salesforce",
    title: "Hosted MCP Invocable Actions",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/invocable-actions.html",
    kind: "mcp",
  },
  {
    id: "salesforce-hosted-prompt-builder",
    product: "Salesforce",
    title: "Hosted MCP Prompt Builder",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/references/reference/prompt-builder.html",
    kind: "mcp",
  },
  {
    id: "salesforce-cli",
    product: "Salesforce",
    title: "Salesforce CLI",
    url: "https://developer.salesforce.com/tools/salesforcecli",
    kind: "cli",
  },
  {
    id: "agentforce-vibes-mcp-client",
    product: "Agentforce",
    title: "Agentforce Vibes MCP Tools",
    url: "https://developer.salesforce.com/docs/platform/einstein-for-devs/guide/devagent-mcp.html",
    kind: "mcp",
  },
  {
    id: "salesforce-rest-api",
    product: "Salesforce",
    title: "Salesforce Platform REST API Overview",
    url: "https://developer.salesforce.com/blogs/2024/04/accessing-object-data-with-salesforce-platform-apis",
    kind: "api",
  },
  {
    id: "data360-mcp-preview",
    product: "Data 360",
    title: "Data 360 MCP Server Developer Preview",
    url: "https://developer.salesforce.com/blogs/2026/05/introducing-the-data-360-mcp-server-developer-preview",
    kind: "mcp",
  },
  {
    id: "data360-hosted-mcp",
    product: "Data 360",
    title: "Hosted MCP Data 360 SQL",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/guide/data-cloud-sql.html",
    kind: "mcp",
  },
  {
    id: "tableau-next-mcp",
    product: "Tableau Next",
    title: "Hosted MCP Tableau Next",
    url: "https://developer.salesforce.com/docs/platform/hosted-mcp-servers/references/reference/tableau-next.html",
    kind: "mcp",
  },
  {
    id: "heroku-remote-mcp",
    product: "Heroku",
    title: "Heroku Remote MCP Server",
    url: "https://devcenter.heroku.com/articles/heroku-remote-mcp-server",
    kind: "mcp",
  },
  {
    id: "heroku-platform-api",
    product: "Heroku",
    title: "Heroku Platform API Reference",
    url: "https://devcenter.heroku.com/articles/platform-api-reference",
    kind: "api",
  },
  {
    id: "heroku-cli",
    product: "Heroku",
    title: "Heroku CLI",
    url: "https://devcenter.heroku.com/articles/heroku-cli",
    kind: "cli",
  },
  {
    id: "mulesoft-mcp-server",
    product: "MuleSoft",
    title: "MuleSoft MCP Server",
    url: "https://docs.mulesoft.com/mulesoft-mcp-server/",
    kind: "mcp",
  },
  {
    id: "mulesoft-mcp-connector",
    product: "MuleSoft",
    title: "Anypoint Connector for MCP",
    url: "https://docs.mulesoft.com/mcp-connector/1.2/",
    kind: "mcp",
  },
  {
    id: "anypoint-cli",
    product: "MuleSoft",
    title: "Anypoint CLI",
    url: "https://docs.mulesoft.com/anypoint-cli/latest/",
    kind: "cli",
  },
  {
    id: "slack-mcp",
    product: "Slack",
    title: "Slack MCP Server",
    url: "https://docs.slack.dev/ai/mcp-server/",
    kind: "mcp",
  },
  {
    id: "slack-web-api",
    product: "Slack",
    title: "Slack Web API",
    url: "https://docs.slack.dev/apis/web-api",
    kind: "api",
  },
  {
    id: "slack-cli",
    product: "Slack",
    title: "Slack CLI",
    url: "https://docs.slack.dev/tools/slack-cli/",
    kind: "cli",
  },
  {
    id: "informatica-acquisition",
    product: "Informatica",
    title: "Salesforce Completes Acquisition of Informatica",
    url: "https://www.salesforce.com/news/press-releases/2025/11/18/salesforce-completes-acquisition-of-informatica/",
    kind: "press",
  },
  {
    id: "informatica-idmc-rest",
    product: "Informatica",
    title: "IDMC REST API Reference",
    url: "https://docs.informatica.com/integration-cloud/cloud-platform/current-version/rest-api-reference/informatica-intelligent-cloud-services-rest-api.html",
    kind: "api",
  },
];
