/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SourceManagerRouteImport } from './routes/source-manager'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesNamespaceRouteImport } from './routes/sources.$namespace'
import { Route as SourcesAddPluginKeyRouteImport } from './routes/sources.add.$pluginKey'
import { Route as PluginsPluginIdSplatRouteImport } from './routes/plugins.$pluginId.$'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceManagerRoute = SourceManagerRouteImport.update({
  id: '/source-manager',
  path: '/source-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNamespaceRoute = SourcesNamespaceRouteImport.update({
  id: '/$namespace',
  path: '/$namespace',
  getParentRoute: () => SourcesRoute,
} as any)
const SourcesAddPluginKeyRoute = SourcesAddPluginKeyRouteImport.update({
  id: '/add/$pluginKey',
  path: '/add/$pluginKey',
  getParentRoute: () => SourcesRoute,
} as any)
const PluginsPluginIdSplatRoute = PluginsPluginIdSplatRouteImport.update({
  id: '/plugins/$pluginId/$',
  path: '/plugins/$pluginId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/source-manager': typeof SourceManagerRoute
  '/sources': typeof SourcesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/source-manager': typeof SourceManagerRoute
  '/sources': typeof SourcesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/policies': typeof PoliciesRoute
  '/secrets': typeof SecretsRoute
  '/source-manager': typeof SourceManagerRoute
  '/sources': typeof SourcesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/sources/$namespace': typeof SourcesNamespaceRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/sources/add/$pluginKey': typeof SourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/policies'
    | '/secrets'
    | '/source-manager'
    | '/sources'
    | '/tools'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/policies'
    | '/secrets'
    | '/source-manager'
    | '/sources'
    | '/tools'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/policies'
    | '/secrets'
    | '/source-manager'
    | '/sources'
    | '/tools'
    | '/sources/$namespace'
    | '/plugins/$pluginId/$'
    | '/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  PoliciesRoute: typeof PoliciesRoute
  SecretsRoute: typeof SecretsRoute
  SourceManagerRoute: typeof SourceManagerRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  PluginsPluginIdSplatRoute: typeof PluginsPluginIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-manager': {
      id: '/source-manager'
      path: '/source-manager'
      fullPath: '/source-manager'
      preLoaderRoute: typeof SourceManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$namespace': {
      id: '/sources/$namespace'
      path: '/$namespace'
      fullPath: '/sources/$namespace'
      preLoaderRoute: typeof SourcesNamespaceRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/sources/add/$pluginKey': {
      id: '/sources/add/$pluginKey'
      path: '/add/$pluginKey'
      fullPath: '/sources/add/$pluginKey'
      preLoaderRoute: typeof SourcesAddPluginKeyRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/plugins/$pluginId/$': {
      id: '/plugins/$pluginId/$'
      path: '/plugins/$pluginId/$'
      fullPath: '/plugins/$pluginId/$'
      preLoaderRoute: typeof PluginsPluginIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SourcesRouteChildren {
  SourcesNamespaceRoute: typeof SourcesNamespaceRoute
  SourcesAddPluginKeyRoute: typeof SourcesAddPluginKeyRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesNamespaceRoute: SourcesNamespaceRoute,
  SourcesAddPluginKeyRoute: SourcesAddPluginKeyRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  PoliciesRoute: PoliciesRoute,
  SecretsRoute: SecretsRoute,
  SourceManagerRoute: SourceManagerRoute,
  SourcesRoute: SourcesRouteWithChildren,
  ToolsRoute: ToolsRoute,
  PluginsPluginIdSplatRoute: PluginsPluginIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
